enigma2-plugins: Fix missing build dependencies
RROR: enigma2-plugins-2.0-git-r0 do_package_qa: QA Issue: enigma2-plugin-extensions-imdb rdepends on python3-six, but it isn't a build dependency,
missing python3-six in DEPENDS or PACKAGECONFIG? [build-deps]
ERROR: enigma2-plugins-2.0-git-r0 do_package_qa: QA Issue: enigma2-plugin-extensions-dvdbackup rdepends on dvdbackup, but it isn't a build dependency,
missing dvdbackup in DEPENDS or PACKAGECONFIG? [build-deps]
ERROR: enigma2-plugins-2.0-git-r0 do_package_qa: QA Issue: enigma2-plugin-extensions-dvdbackup rdepends on libdvdread, but it isn't a build dependency,
missing libdvdread in DEPENDS or PACKAGECONFIG? [build-deps]
ERROR: enigma2-plugins-2.0-git-r0 do_package_qa: Fatal QA errors were found, failing task.