gstreamer: update to git master head Apply patch to fix build. Patch revert commit: https://cgit.freedesktop.org/gstreamer/gst-plugins-good/commit/?id=24f01944ee0df123f3948ec756a1ca11cc64a824
Due to error:
./../../git/sys/v4l2/gstv4l2object.c:516:22: error: assignment from incompatible pointer type [-Werror=incompatible-pointer-types]
|      v4l2object->mmap = mmap;