reporefs.conf: Remove SRCREV python-transmissionrpc
To fix error:

ERROR: /home/hains/openpli-dm920-python3/meta-openpli/recipes-devtools/python/python-transmissionrpc_hg.bb:
AUTOREV/SRCPV set too late for the fetcher to work properly, please set the variables earlier in parsing.
Erroring instead of later obtuse build failures.
ERROR: Parsing halted due to errors, see error messages above

Introduced with:
https://git.openembedded.org/bitbake/commit/?id=4d9ec332d5bfc8b60b54f8ec2a17d34e35aa903a