enigma2: Use integer instead of float
Error introduced with Python 3.10:

 File "/usr/lib/enigma2/python/Screens/Screen.py", line 271, in createGUIScreen
    f()
  File "/usr/lib/enigma2/python/Screens/SkinSelector.py", line 90, in layoutFinished
    self.picload.setPara((self["preview"].instance.size().width(), self["preview"].instance.size().height(), 1.0, 1, 1, 1, "#ff000000"))
SystemError: <built-in function ePicLoad_setPara> returned a result with an exception set