libpassthrough: restore INSANE_SKIP to fix build
To fix error:
ERROR: libpassthrough-0.6-r0 do_package_qa: QA Issue: /usr/lib/libpassthrough.so contained in package libpassthrough
requires libssl.so.1.0.0, but no providers found in RDEPENDS_libpassthrough? [file-rdeps]

Thanks Open Alliance.