coreutils: fix build
ERROR: Nothing RPROVIDES 'coreutils-realpath' (but /home/hains/openvision-dm920-oe-core/meta-dream/recipes-bsp/
recovery/recovery_1.1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'coreutils-realpath' is unbuildable, removing...