openpli.conf: remove x11 from DISTRO_FEATURES
As it breaks the build of vim.

compilation terminated.
| make: *** [Makefile:2979: objects/gui_gtk.o] Error 1
| make: *** Waiting for unfinished jobs....
| gui_gtk_f.c:38:11: fatal error: gdk/gdkx.h: No such file or directory
|  # include <gdk/gdkx.h>

Introduced with commit:
https://github.com/Hains/openpli-dm8000-oe-core/commit/7de9daef095882212a79bdb7fc0db96bd8fa1259