gstreamer: update to git HEAD
Gstreamer-plugins-base:
-Apply patch to fix build.

../../../../git/gst-libs/gst/pbutils/gstdiscoverer.c:1800:26: error: format '%u' expects argument of type 'unsigned int',
but argument 3 has type '__off64_t' {aka 'long long int'} [-Werror=format=]
    tmp = g_strdup_printf ("%s-%" G_GSIZE_FORMAT "-%" G_GINT64_FORMAT,

 ../../../../git/gst-libs/gst/pbutils/gstdiscoverer.c:1800:26: error: format '%lli' expects argument of type 'long long int',
but argument 4 has type '__time_t' {aka 'long int'} [-Werror=format=]
    tmp = g_strdup_printf ("%s-%" G_GSIZE_FORMAT "-%" G_GINT64_FORMAT,

Gstreamer-plugins-bad:
-Remove redundant jpeg and libpng dependencies.
https://git.openembedded.org/openembedded-core/commit/?h=master-next&id=0075931776b8ba359370252b9fcfc9586017d8de
(jpeg only).
-Remove opus from PACKAGECONFIG and update PACKAGECONFIG to sync more with yocto project.

Gstreamer-plugins-ugly:
-Remove redundant libid3tag dependency.
https://git.openembedded.org/openembedded-core/commit/?h=master-next&id=da48cb977804cbabe3d2746ffe3895f7000b578b