python: fix build
File: '/usr/lib/python3.6/json/decoder.py', lineno: 357, function: raw_decode
     0353:        """
     0354:        try:
     0355:            obj, end = self.scan_once(s, idx)
     0356:        except StopIteration as err:
 *** 0357:            raise JSONDecodeError("Expecting value", s, err.value) from None
     0358:        return obj, end
Exception: json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

ERROR: Failed to parse recipe: /home/hains/openpli-dm8000-oe-core/openembedded-core/meta/recipes-devtools/python/python_2.7.15.b

Introduced with commit:
http://cgit.openembedded.org/openembedded-core/commit/?id=5641a24a70b54544012c04c6a082514d9a5aa49a