wsdd: Fix unused result error
https://github.com/openembedded/openembedded-core/commit/4c2d64c10a5b0437ab1ea04df22386f0f95124d1

 wsdd.c: In function 'readSmbConf':
| wsdd.c:201:17: error: ignoring return value of 'fgets' declared with attribute 'warn_unused_result' [-Werror=unused-result]
|   201 |                 fgets(cd_name, sizeof(cd_name)-1, fp);
|       |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| wsdd.c:212:17: error: ignoring return value of 'fgets' declared with attribute 'warn_unused_result' [-Werror=unused-result]
|   212 |                 fgets(cd_workgroup, sizeof(cd_workgroup)-1, fp);
|       |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~