dvd+rw-tools: fix build with glibc 2.28
glibc 2.28 no longer defines 'major' and 'minor' in <sys/types.h> and
requires us to include <sys/sysmacros.h>.

/usr/src/debug/dvd+rw-tools/7.1-r4/dvd+rw-tools-7.1/growisofs.c:704: undefined reference to `minor'
| collect2: error: ld returned 1 exit status