gnupg: fix build
ERROR: Nothing RPROVIDES 'gpgv' (but /home/hains/openvision-dm920-oe-core/meta-dream/recipes-bsp/
recovery/recovery_1.1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'gpgv' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['gpgv']