mjpegtools: Upgrade to 2.2.1
Add bash to RDEPENDS to fix build.

ERROR: mjpegtools-2.2.1-r0 do_package_qa: QA Issue: /usr/bin/lavtc.sh contained in package mjpegtools
requires /bin/bash, but no providers found in RDEPENDS:mjpegtools? [file-rdeps]
ERROR: mjpegtools-2.2.1-r0 do_package_qa: Fatal QA errors were found, failing task.