openpli.conf: Drop opengl ptest multiarch wayland vulkan from DISTRO_FEATURES_BACKFILL
We don't need it, and it breaks the build

ERROR: Nothing PROVIDES 'virtual/egl' (but /home/hains/openpli-dm920-python3/openembedded-core/meta/recipes-multimedia/
gstreamer/gstreamer1.0-plugins-base_1.26.9.bb DEPENDS on or otherwise requires it)

Reverts commit:
https://github.com/openembedded/openembedded-core/commit/2e1e7c86064ce36580953650b27cca9ae7c269c4