python3-levenshtein: Downgrade to 0.25.1
0.26.1 is just a fallback for compatibility with useless wheel and text files.
Package has been renamed to levenshtein
https://github.com/rapidfuzz/Levenshtein

Doesn't cross compile for now.

Downgrade back to 0.25.1 and apply patch to fix build:

/home/hains/openpli-dm920-python3/build/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/python3-levenshtein/0.25.1/Levenshtein-0.25.1/
src/Levenshtein/levenshtein_cpp.cxx:8822:42: error: too few arguments to function 'int _PyLong_AsByteArray(PyLongObject*, unsigned char*, size_t, int, int, int)'
|  8822 |                 ret = _PyLong_AsByteArray((PyLongObject *)v,
|       |                       ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
|  8823 |                                            bytes, sizeof(val),
|       |                                            ~~~~~~~~~~~~~~~~~~~
|  8824 |                                            is_little, !is_unsigned);
|       |                                            ~~~~~~~~~~~~~~~~~~~~~~~~

Based on:
https://github.com/AdamWill/pyodbc/commit/456ddac64630f7bf0a4931b5070c3b57138490c6