enigma2: Remove register keyword
Keyword 'register' is deprecated with C++17

../../git/lib/gdi/font.cpp:1102:38: error: ISO C++17 does not allow 'register' storage class specifier [-Werror=register]
|  1102 |                         register int sx = sxbase;
|       |                                      ^~
| ../../git/lib/gdi/font.cpp:1131:54: error: ISO C++17 does not allow 'register' storage class specifier [-Werror=register]
|  1131 |                                         register int extra_buffer_stride = buffer_stride - sx;
|       |                                                      ^~~~~~~~~~~~~~~~~~~
| ../../git/lib/gdi/font.cpp:1132:56: error: ISO C++17 does not allow 'register' storage class specifier [-Werror=register]
|  1132 |                                         register __u8 *td=d;
|       |                                                        ^~