gnupg: Remove package append
ERROR: Nothing RPROVIDES 'gnupg-gpggpgv' (but /home/hains/openvision-dm920-python3/
openembedded-core/meta/recipes-support/gnupg/gnupg_2.3.3.bb RDEPENDS on or otherwise requires it)