spdlog: Fix build Gerbera against latest git fmt
Introduced with commit:
https://github.com/fmtlib/fmt/commit/8f18e72df576ebfbd088a57a5c6cae8d4d0fc3dc

/home/hains/openpli-dm920-python3/build/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/gerbera/1.12.1-r0/git/src/config/config_manager.cc:108:5:   required from here
| /home/hains/openpli-dm920-python3/build/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/gerbera/1.12.1-r0/recipe-sysroot/usr/include/spdlog/logger.h:374:75:
error: cannot bind non-const lvalue reference of type 'const char*&' to an rvalue of type 'const char*'
|   374 |             fmt::vformat_to(fmt::appender(buf), fmt, fmt::make_format_args(std::forward<Args>(args)...));
|       |                                                      ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Cast to rvaluas.