filecommander: Convert key_action.hashes keys to list
Without converting, the result will be: dict_keys(['MD5', 'SHA1', 'SHA3', 'SHA256', 'SHA512'])
Causing error:

 File "/usr/lib/enigma2/python/Components/config.py", line 1315, in __init__
    assert False, "ConfigSet choices must be a list!"
AssertionError: ConfigSet choices must be a list!

Apply patch as 'assert' doesn't work with OpenPLi due to optimization option.