enigma2: Fix build
Probably by:
https://github.com/openembedded/openembedded-core/commit/4c2d64c10a5b0437ab1ea04df22386f0f95124d1

../../sources/enigma2-3.14+git/lib/gdi/lcd.cpp:247:22: error: ignoring return value of
'ssize_t write(int, const void*, size_t)' declared with attribute 'warn_unused_result' [-Werror=unused-result]
|   247 |                 write(lcdfd, raw, 132 * 8);
|       |                 ~~~~~^~~~~~~~~~~~~~~~~~~~~
| ../../sources/enigma2-3.14+git/lib/gdi/lcd.cpp:268:30: error: ignoring return value of
'ssize_t write(int, const void*, size_t)' declared with attribute 'warn_unused_result' [-Werror=unused-result]
|   268 |                         write(lcdfd, raw, _stride * height);
|       |                         ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~