image_types_tarbz2: Tryfix for openvision-enigma2-image.bb:do_image_tar
Error:

ERROR: openvision-enigma2-image-1.0-r0 do_image_tar: Taskhash mismatch 00891262334525e247bc1c7a56c9de28ae066a6ad5190c5c1f3904c589f5c259 versus
66a32a2b8ef6b7acf8675d513e8c0d811a4b0fc3ae534f82444ddeecffcc7a34 for /home/hains/openvision-dm920-python3/meta-openvision/recipes-openvision/images/openvision-enigma2-image.bb:do_image_tar
ERROR: Taskhash mismatch 00891262334525e247bc1c7a56c9de28ae066a6ad5190c5c1f3904c589f5c259 versus
66a32a2b8ef6b7acf8675d513e8c0d811a4b0fc3ae534f82444ddeecffcc7a34 for /home/hains/openvision-dm920-python3/meta-openvision/recipes-openvision/images/openvision-enigma2-image.bb:do_image_tar

When date has been changed.