fmt: Update to latest git revision
Apply patch to revert commit:
https://github.com/fmtlib/fmt/commit/13156e54bf91e44641ce3aac041d31f9a15a8042
partially, to fix compile error:

/home/hains/openpli-dm920-python3/build/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/spdlog/1.11.pre1-r0/
git/include/spdlog/fmt/fmt.h:31:14: fatal error: fmt/core.h: No such file or directory