enigma2: Fix 'Errno 16] Device or resource busy' error
Introduced with Python 3.13.0.

Traceback (most recent call last):
  File "/usr/lib/enigma2/python/Tools/Profile.py", line 44, in profile
    open("/proc/progress", "w").write("%d \n" % perc)
OSError: [Errno 16] Device or resource busy
Exception ignored in: <_io.TextIOWrapper name='/proc/progress' mode='w' encoding='UTF-8'>