libupnp: update to 1.6.22 Update to fix build.
openpli-dm8000-oe-core/build/tmp/work/mips32el-oe-linux/libupnp/1.6.5-r1/build/ixml/.libs/libixml.so ../../
threadutil/.libs/libthreadutil.so ../../ixml/.libs/libixml.so -pthread
../../upnp/.libs/libupnp.so: undefined reference to `get_content_type'
collect2: error: ld returned 1 exit status
Makefile:518: recipe for target 'upnp_tv_ctrlpt' failed
make[3]: *** [upnp_tv_ctrlpt] Error 1

-Remove duplicate recipe.