tmbd: Fix first hunk of patch not applied
Typo. Introduced with
https://github.com/Hains/openpli-dm920-python3/commit/8095badd88ac231774f9201a641c1651ae0b50a7

Fix:

File "/usr/lib/enigma2/python/Plugins/Extensions/TMBD/tmbdYTTrailer.py", line 231, in createThumbnails
    callInThread(self.threadDownloadPage, entry[2].encode(), os.path.join('/tmp/', str(entry[0]) + '.jpg'),\
    ^^^^^^^^^^^^
NameError: name 'callInThread' is not defined