enigma2: fix build with gcc 7
../../git/lib/dvb/scan.cpp: In member function 'RESULT eDVBScan::startFilter()':
| ../../git/lib/dvb/scan.cpp:310:54: error: call of overloaded 'abs(unsigned int)' is ambiguous
|       if ((tsid == 0x00d7 && abs(parm.frequency-618000) < 2000) ||
|                               ^

Use fabs() instead of abs().