enigma2: fix crash Menu-Setup-System-Expert settings-Record
Introduced with commit:
https://github.com/OpenPLi/enigma2/commit/bab01517e80e26dc36d3d42a47b3a0d447f10d6d

[Skin] Processing screen: Setup
warning, skin is missing element HelpWindow in <class 'Screens.Setup.Setup'>
[Skin] Attribute not implemented: itemHeight value: 38
[Skin] Processing screen: SetupSummary
Traceback (most recent call last):
  File "/usr/lib/enigma2/python/Components/ConfigList.py", line 74, in selectionChanged
  File "/usr/lib/enigma2/python/Components/ConfigList.py", line 196, in handleInputHelpers
AttributeError: 'NoneType' object has no attribute 'instance'

Reverts the regarding commit partially for now.