image_types_nfi.bbclass: fix do_image_ubifs
Replace DEPLOY_DIR_IMAGE with IMGDEPLOYDIR for rootfs.ubifs files.

ERROR: openpli-enigma2-image-1.0-r0 do_image_complete: The recipe openpli-enigma2-image is trying to install files into a shared area
when those files already exist. Those files and their manifest location are:
/home/hains/openpli-dm8000-oe-core/build/tmp/deploy/images/dm8000/openpli-enigma2-8.2-dm8000.rootfs.ubifs
(not matched to any task)
Please verify which recipe should provide the above files.

Introduced with commit:
https://github.com/openembedded/openembedded-core/commit/05f6042a40bb772f7ce8d6819c5b2937d8c9808d