Remove ${PN}-src and do_split_packages
Introduced with commit:
https://git.openembedded.org/openembedded-core/commit/?id=8df14b678e44cc749b361224af05ccbcfa9ae9b5

To fix build errors like:
ERROR: python-six-1.11.0-r0 do_package: QA Issue: python-six-src is listed in PACKAGES multiple times, this leads to packaging errors. [packages-list]
ERROR: python-six-1.11.0-r0 do_package: Fatal QA errors found, failing task.
ERROR: python-six-1.11.0-r0 do_package: Function failed: do_package
ERROR: Logfile of failure stored in: /home/hains/openpli-dm8000-oe-core/build/tmp/work/mips32el-oe-linux/python-six/1.11.0-r0/temp/log.do_package.32109
ERROR: Task (/home/hains/openpli-dm8000-oe-core/meta-openembedded/meta-python/recipes-devtools/python/python-six_1.11.0.bb:do_package) failed with exit code '1'